/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cubit Control Plane API
 * Strict REST API for Cubit, an open-source bare-metal PaaS for running Cloudflare Workers and Durable Objects using celld, Traefik, and S3 storage.
 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationMetricsRequestsByCountry } from './applicationMetricsRequestsByCountry';
import type { ApplicationMetricsRequestsByColo } from './applicationMetricsRequestsByColo';
import type { RequestLogEvent } from './requestLogEvent';

export interface ApplicationMetrics {
  totalRequests: number;
  status2xx: number;
  status4xx: number;
  status5xx: number;
  avgDurationMs: number;
  p99DurationMs: number;
  successRate?: number;
  errorRate?: number;
  requestsByCountry?: ApplicationMetricsRequestsByCountry;
  requestsByColo?: ApplicationMetricsRequestsByColo;
  /** @nullable */
  lastInvokedAt?: string | null;
  recentEvents?: RequestLogEvent[];
}
