/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cubit Control Plane API
 * Strict REST API for Cubit, an open-source bare-metal PaaS for running Cloudflare Workers and Durable Objects using celld, Traefik, and S3 storage.
 * OpenAPI spec version: 1.0.0
 */

export type DeploymentLogEntryStep = typeof DeploymentLogEntryStep[keyof typeof DeploymentLogEntryStep];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeploymentLogEntryStep = {
  git_clone: 'git_clone',
  esbuild: 'esbuild',
  s3_upload: 's3_upload',
  celld_deploy: 'celld_deploy',
  route_sync: 'route_sync',
} as const;
