/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cubit Control Plane API
 * Strict REST API for Cubit, an open-source bare-metal PaaS for running Cloudflare Workers and Durable Objects using celld, Traefik, and S3 storage.
 * OpenAPI spec version: 1.0.0
 */
import type { RequestLogEventRequestHeaders } from './requestLogEventRequestHeaders';
import type { RequestLogEventResponseHeaders } from './requestLogEventResponseHeaders';
import type { ConsoleLogEntry } from './consoleLogEntry';

export interface RequestLogEvent {
  id: string;
  timestamp: string;
  method: string;
  path: string;
  url: string;
  statusCode: number;
  durationMs: number;
  clientIp: string;
  message?: string;
  outcome?: string;
  requestHeaders?: RequestLogEventRequestHeaders;
  requestBody?: string;
  responseHeaders?: RequestLogEventResponseHeaders;
  responseBody?: string;
  logs?: ConsoleLogEntry[];
  exceptions?: string[];
}
