/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cubit Control Plane API
 * Strict REST API for Cubit, an open-source bare-metal PaaS for running Cloudflare Workers and Durable Objects using celld, Traefik, and S3 storage.
 * OpenAPI spec version: 1.0.0
 */

export type ResourceBindingType = typeof ResourceBindingType[keyof typeof ResourceBindingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceBindingType = {
  kv_namespace: 'kv_namespace',
  d1_database: 'd1_database',
  r2_bucket: 'r2_bucket',
  queue: 'queue',
  workflow: 'workflow',
  service: 'service',
  durable_object: 'durable_object',
  container: 'container',
  assets: 'assets',
} as const;
