/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cubit Control Plane API
 * Strict REST API for Cubit, an open-source bare-metal PaaS for running Cloudflare Workers and Durable Objects using celld, Traefik, and S3 storage.
 * OpenAPI spec version: 1.0.0
 */

export type RuntimeStatusStorageBackend = typeof RuntimeStatusStorageBackend[keyof typeof RuntimeStatusStorageBackend];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RuntimeStatusStorageBackend = {
  garage_local: 'garage_local',
  cloudflare_r2: 'cloudflare_r2',
  aws_s3: 'aws_s3',
  custom_s3: 'custom_s3',
} as const;
