/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Cubit Control Plane API
 * Strict REST API for Cubit, an open-source bare-metal PaaS for running Cloudflare Workers and Durable Objects using celld, Traefik, and S3 storage.
 * OpenAPI spec version: 1.0.0
 */
import type { WranglerImportRequestFormat } from './wranglerImportRequestFormat';

export interface WranglerImportRequest {
  /** Raw content of wrangler.json, wrangler.jsonc, or wrangler.toml */
  rawConfig: string;
  format?: WranglerImportRequestFormat;
  /** Optional environment name override (e.g. staging, production) */
  env?: string;
}
