// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApplicationStatus.
const (
	ApplicationStatusBuilding ApplicationStatus = "building"
	ApplicationStatusCreated  ApplicationStatus = "created"
	ApplicationStatusFailed   ApplicationStatus = "failed"
	ApplicationStatusRunning  ApplicationStatus = "running"
	ApplicationStatusStopped  ApplicationStatus = "stopped"
)

// Valid indicates whether the value is a known member of the ApplicationStatus enum.
func (e ApplicationStatus) Valid() bool {
	switch e {
	case ApplicationStatusBuilding:
		return true
	case ApplicationStatusCreated:
		return true
	case ApplicationStatusFailed:
		return true
	case ApplicationStatusRunning:
		return true
	case ApplicationStatusStopped:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentLogEntryLevel.
const (
	Error DeploymentLogEntryLevel = "error"
	Info  DeploymentLogEntryLevel = "info"
	Warn  DeploymentLogEntryLevel = "warn"
)

// Valid indicates whether the value is a known member of the DeploymentLogEntryLevel enum.
func (e DeploymentLogEntryLevel) Valid() bool {
	switch e {
	case Error:
		return true
	case Info:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentLogEntryStep.
const (
	CelldDeploy DeploymentLogEntryStep = "celld_deploy"
	Esbuild     DeploymentLogEntryStep = "esbuild"
	GitClone    DeploymentLogEntryStep = "git_clone"
	RouteSync   DeploymentLogEntryStep = "route_sync"
	S3Upload    DeploymentLogEntryStep = "s3_upload"
)

// Valid indicates whether the value is a known member of the DeploymentLogEntryStep enum.
func (e DeploymentLogEntryStep) Valid() bool {
	switch e {
	case CelldDeploy:
		return true
	case Esbuild:
		return true
	case GitClone:
		return true
	case RouteSync:
		return true
	case S3Upload:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentStatus.
const (
	DeploymentStatusActive     DeploymentStatus = "active"
	DeploymentStatusBuilding   DeploymentStatus = "building"
	DeploymentStatusDeploying  DeploymentStatus = "deploying"
	DeploymentStatusFailed     DeploymentStatus = "failed"
	DeploymentStatusPending    DeploymentStatus = "pending"
	DeploymentStatusSuperseded DeploymentStatus = "superseded"
)

// Valid indicates whether the value is a known member of the DeploymentStatus enum.
func (e DeploymentStatus) Valid() bool {
	switch e {
	case DeploymentStatusActive:
		return true
	case DeploymentStatusBuilding:
		return true
	case DeploymentStatusDeploying:
		return true
	case DeploymentStatusFailed:
		return true
	case DeploymentStatusPending:
		return true
	case DeploymentStatusSuperseded:
		return true
	default:
		return false
	}
}

// Defines values for NodeStatus.
const (
	NodeStatusActive   NodeStatus = "active"
	NodeStatusDraining NodeStatus = "draining"
	NodeStatusOffline  NodeStatus = "offline"
)

// Valid indicates whether the value is a known member of the NodeStatus enum.
func (e NodeStatus) Valid() bool {
	switch e {
	case NodeStatusActive:
		return true
	case NodeStatusDraining:
		return true
	case NodeStatusOffline:
		return true
	default:
		return false
	}
}

// Defines values for ResourceBindingType.
const (
	D1Database  ResourceBindingType = "d1_database"
	KvNamespace ResourceBindingType = "kv_namespace"
	Queue       ResourceBindingType = "queue"
	R2Bucket    ResourceBindingType = "r2_bucket"
	Workflow    ResourceBindingType = "workflow"
)

// Valid indicates whether the value is a known member of the ResourceBindingType enum.
func (e ResourceBindingType) Valid() bool {
	switch e {
	case D1Database:
		return true
	case KvNamespace:
		return true
	case Queue:
		return true
	case R2Bucket:
		return true
	case Workflow:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusStorageBackend.
const (
	AwsS3        RuntimeStatusStorageBackend = "aws_s3"
	CloudflareR2 RuntimeStatusStorageBackend = "cloudflare_r2"
	CustomS3     RuntimeStatusStorageBackend = "custom_s3"
	GarageLocal  RuntimeStatusStorageBackend = "garage_local"
)

// Valid indicates whether the value is a known member of the RuntimeStatusStorageBackend enum.
func (e RuntimeStatusStorageBackend) Valid() bool {
	switch e {
	case AwsS3:
		return true
	case CloudflareR2:
		return true
	case CustomS3:
		return true
	case GarageLocal:
		return true
	default:
		return false
	}
}

// Defines values for SourceType.
const (
	Git    SourceType = "git"
	Inline SourceType = "inline"
)

// Valid indicates whether the value is a known member of the SourceType enum.
func (e SourceType) Valid() bool {
	switch e {
	case Git:
		return true
	case Inline:
		return true
	default:
		return false
	}
}

// Application defines model for Application.
type Application struct {
	ActiveDeploymentId *openapi_types.UUID    `json:"activeDeploymentId,omitempty"`
	Bindings           *[]ResourceBinding     `json:"bindings,omitempty"`
	Branch             *string                `json:"branch,omitempty"`
	CreatedAt          time.Time              `json:"createdAt"`
	EnvVars            *[]EnvironmentVariable `json:"envVars,omitempty"`
	GitRepo            *string                `json:"gitRepo,omitempty"`
	Id                 openapi_types.UUID     `json:"id"`
	InlineCode         *string                `json:"inlineCode,omitempty"`
	Name               string                 `json:"name"`
	SourceType         SourceType             `json:"sourceType"`
	Status             ApplicationStatus      `json:"status"`
	Subdomain          *string                `json:"subdomain,omitempty"`
	TestUrl            *string                `json:"testUrl,omitempty"`
	UpdatedAt          time.Time              `json:"updatedAt"`
}

// ApplicationStatus defines model for Application.Status.
type ApplicationStatus string

// CreateApplicationRequest defines model for CreateApplicationRequest.
type CreateApplicationRequest struct {
	Bindings   *[]ResourceBinding     `json:"bindings,omitempty"`
	Branch     *string                `json:"branch,omitempty"`
	EnvVars    *[]EnvironmentVariable `json:"envVars,omitempty"`
	GitRepo    *string                `json:"gitRepo,omitempty"`
	InlineCode *string                `json:"inlineCode,omitempty"`
	Name       string                 `json:"name"`
	SourceType *SourceType            `json:"sourceType,omitempty"`
}

// CreateDeploymentRequest defines model for CreateDeploymentRequest.
type CreateDeploymentRequest struct {
	CommitHash   *string `json:"commitHash,omitempty"`
	ForceRebuild *bool   `json:"forceRebuild,omitempty"`
}

// CreateDomainRequest defines model for CreateDomainRequest.
type CreateDomainRequest struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`
	Hostname      string             `json:"hostname"`
	PathPrefix    *string            `json:"pathPrefix,omitempty"`
}

// CreateNodeRequest defines model for CreateNodeRequest.
type CreateNodeRequest struct {
	InternalPort *int   `json:"internalPort,omitempty"`
	IpAddress    string `json:"ipAddress"`
	Name         string `json:"name"`
	WorkerPort   *int   `json:"workerPort,omitempty"`
}

// Deployment defines model for Deployment.
type Deployment struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`

	// BuildVersion Sequential build version for this application (e.g. 1 for v1)
	BuildVersion  *int               `json:"buildVersion,omitempty"`
	BundleSize    *int               `json:"bundleSize,omitempty"`
	CommitHash    string             `json:"commitHash"`
	CommitMessage *string            `json:"commitMessage,omitempty"`
	CreatedAt     time.Time          `json:"createdAt"`
	ErrorMessage  *string            `json:"errorMessage,omitempty"`
	FinishedAt    *time.Time         `json:"finishedAt,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	Status        DeploymentStatus   `json:"status"`
}

// DeploymentLogEntry defines model for DeploymentLogEntry.
type DeploymentLogEntry struct {
	Level     DeploymentLogEntryLevel `json:"level"`
	Message   string                  `json:"message"`
	Step      DeploymentLogEntryStep  `json:"step"`
	Timestamp time.Time               `json:"timestamp"`
}

// DeploymentLogEntryLevel defines model for DeploymentLogEntry.Level.
type DeploymentLogEntryLevel string

// DeploymentLogEntryStep defines model for DeploymentLogEntry.Step.
type DeploymentLogEntryStep string

// DeploymentStatus defines model for DeploymentStatus.
type DeploymentStatus string

// Domain defines model for Domain.
type Domain struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`
	CreatedAt     time.Time          `json:"createdAt"`
	Hostname      string             `json:"hostname"`
	Id            openapi_types.UUID `json:"id"`
	PathPrefix    string             `json:"pathPrefix"`
	SslActive     bool               `json:"sslActive"`
}

// EnvironmentVariable defines model for EnvironmentVariable.
type EnvironmentVariable struct {
	IsSecret *bool  `json:"isSecret,omitempty"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string    `json:"code"`
	Details *[]string `json:"details,omitempty"`
	Message string    `json:"message"`
}

// Node defines model for Node.
type Node struct {
	CelldVersion string             `json:"celldVersion"`
	CreatedAt    time.Time          `json:"createdAt"`
	Id           openapi_types.UUID `json:"id"`
	InternalPort int                `json:"internalPort"`
	IpAddress    string             `json:"ipAddress"`
	Name         string             `json:"name"`
	Specs        *NodeSpecs         `json:"specs,omitempty"`
	Status       NodeStatus         `json:"status"`
	WorkerPort   int                `json:"workerPort"`
}

// NodeSpecs defines model for NodeSpecs.
type NodeSpecs struct {
	CpuCores      *int   `json:"cpuCores,omitempty"`
	DiskFreeBytes *int64 `json:"diskFreeBytes,omitempty"`
	MemoryBytes   *int64 `json:"memoryBytes,omitempty"`
}

// NodeStatus defines model for NodeStatus.
type NodeStatus string

// ResourceBinding defines model for ResourceBinding.
type ResourceBinding struct {
	Name       string              `json:"name"`
	ResourceId *string             `json:"resourceId,omitempty"`
	Type       ResourceBindingType `json:"type"`
}

// ResourceBindingType defines model for ResourceBinding.Type.
type ResourceBindingType string

// RuntimeStatus defines model for RuntimeStatus.
type RuntimeStatus struct {
	ActiveNodesCount    int                          `json:"activeNodesCount"`
	CurrentCelldVersion string                       `json:"currentCelldVersion"`
	IsUpgrading         bool                         `json:"isUpgrading"`
	StorageBackend      *RuntimeStatusStorageBackend `json:"storageBackend,omitempty"`
	TargetCelldVersion  *string                      `json:"targetCelldVersion,omitempty"`
}

// RuntimeStatusStorageBackend defines model for RuntimeStatus.StorageBackend.
type RuntimeStatusStorageBackend string

// SourceType defines model for SourceType.
type SourceType string

// TestApplicationRequest defines model for TestApplicationRequest.
type TestApplicationRequest struct {
	Body    *string            `json:"body,omitempty"`
	Headers *map[string]string `json:"headers,omitempty"`
	Method  *string            `json:"method,omitempty"`
	Path    *string            `json:"path,omitempty"`
}

// TestApplicationResponse defines model for TestApplicationResponse.
type TestApplicationResponse struct {
	Body       string             `json:"body"`
	Headers    *map[string]string `json:"headers,omitempty"`
	StatusCode int                `json:"statusCode"`
}

// UpdateApplicationRequest defines model for UpdateApplicationRequest.
type UpdateApplicationRequest struct {
	Bindings   *[]ResourceBinding     `json:"bindings,omitempty"`
	Branch     *string                `json:"branch,omitempty"`
	EnvVars    *[]EnvironmentVariable `json:"envVars,omitempty"`
	InlineCode *string                `json:"inlineCode,omitempty"`
}

// UpgradeDaemonRequest defines model for UpgradeDaemonRequest.
type UpgradeDaemonRequest struct {
	TargetVersion string `json:"targetVersion"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = CreateApplicationRequest

// UpdateApplicationJSONRequestBody defines body for UpdateApplication for application/json ContentType.
type UpdateApplicationJSONRequestBody = UpdateApplicationRequest

// DeployApplicationJSONRequestBody defines body for DeployApplication for application/json ContentType.
type DeployApplicationJSONRequestBody = CreateDeploymentRequest

// TestApplicationJSONRequestBody defines body for TestApplication for application/json ContentType.
type TestApplicationJSONRequestBody = TestApplicationRequest

// CreateDomainJSONRequestBody defines body for CreateDomain for application/json ContentType.
type CreateDomainJSONRequestBody = CreateDomainRequest

// CreateNodeJSONRequestBody defines body for CreateNode for application/json ContentType.
type CreateNodeJSONRequestBody = CreateNodeRequest

// UpgradeCelldDaemonJSONRequestBody defines body for UpgradeCelldDaemon for application/json ContentType.
type UpgradeCelldDaemonJSONRequestBody = UpgradeDaemonRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListApplications List all applications
	// (GET /applications)
	ListApplications(w http.ResponseWriter, r *http.Request)
	// CreateApplication Create a new application
	// (POST /applications)
	CreateApplication(w http.ResponseWriter, r *http.Request)
	// DeleteApplication Delete an application and clean up its routes
	// (DELETE /applications/{id})
	DeleteApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetApplication Get application details
	// (GET /applications/{id})
	GetApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateApplication Update application configuration
	// (PUT /applications/{id})
	UpdateApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// DeployApplication Trigger a new deployment for an application
	// (POST /applications/{id}/deploy)
	DeployApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListDeployments List deployment history for an application
	// (GET /applications/{id}/deployments)
	ListDeployments(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// TestApplication Send a test HTTP request to the active deployment of an application
	// (POST /applications/{id}/test)
	TestApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetDeployment Get deployment details and status
	// (GET /deployments/{id})
	GetDeployment(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetDeploymentLogs Get deployment build and execution logs
	// (GET /deployments/{id}/logs)
	GetDeploymentLogs(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListDomains List all custom domain bindings
	// (GET /domains)
	ListDomains(w http.ResponseWriter, r *http.Request)
	// CreateDomain Add a custom domain route
	// (POST /domains)
	CreateDomain(w http.ResponseWriter, r *http.Request)
	// DeleteDomain Remove a custom domain route
	// (DELETE /domains/{id})
	DeleteDomain(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListNodes List all fleet nodes
	// (GET /nodes)
	ListNodes(w http.ResponseWriter, r *http.Request)
	// CreateNode Register a new bare-metal node
	// (POST /nodes)
	CreateNode(w http.ResponseWriter, r *http.Request)
	// DeleteNode Deregister a node from the fleet
	// (DELETE /nodes/{id})
	DeleteNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetNode Get node details by ID
	// (GET /nodes/{id})
	GetNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// DrainNode Drain a node to safely migrate its active Durable Object leases
	// (POST /nodes/{id}/drain)
	DrainNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetRuntimeStatus Get fleet runtime status and celld version information
	// (GET /runtime/status)
	GetRuntimeStatus(w http.ResponseWriter, r *http.Request)
	// UpgradeCelldDaemon Trigger zero-downtime rolling upgrade of the celld daemon across nodes
	// (POST /runtime/upgrade)
	UpgradeCelldDaemon(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListApplications List all applications
// (GET /applications)
func (_ Unimplemented) ListApplications(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateApplication Create a new application
// (POST /applications)
func (_ Unimplemented) CreateApplication(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteApplication Delete an application and clean up its routes
// (DELETE /applications/{id})
func (_ Unimplemented) DeleteApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetApplication Get application details
// (GET /applications/{id})
func (_ Unimplemented) GetApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateApplication Update application configuration
// (PUT /applications/{id})
func (_ Unimplemented) UpdateApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeployApplication Trigger a new deployment for an application
// (POST /applications/{id}/deploy)
func (_ Unimplemented) DeployApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListDeployments List deployment history for an application
// (GET /applications/{id}/deployments)
func (_ Unimplemented) ListDeployments(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// TestApplication Send a test HTTP request to the active deployment of an application
// (POST /applications/{id}/test)
func (_ Unimplemented) TestApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetDeployment Get deployment details and status
// (GET /deployments/{id})
func (_ Unimplemented) GetDeployment(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetDeploymentLogs Get deployment build and execution logs
// (GET /deployments/{id}/logs)
func (_ Unimplemented) GetDeploymentLogs(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListDomains List all custom domain bindings
// (GET /domains)
func (_ Unimplemented) ListDomains(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateDomain Add a custom domain route
// (POST /domains)
func (_ Unimplemented) CreateDomain(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteDomain Remove a custom domain route
// (DELETE /domains/{id})
func (_ Unimplemented) DeleteDomain(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListNodes List all fleet nodes
// (GET /nodes)
func (_ Unimplemented) ListNodes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateNode Register a new bare-metal node
// (POST /nodes)
func (_ Unimplemented) CreateNode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteNode Deregister a node from the fleet
// (DELETE /nodes/{id})
func (_ Unimplemented) DeleteNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetNode Get node details by ID
// (GET /nodes/{id})
func (_ Unimplemented) GetNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DrainNode Drain a node to safely migrate its active Durable Object leases
// (POST /nodes/{id}/drain)
func (_ Unimplemented) DrainNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetRuntimeStatus Get fleet runtime status and celld version information
// (GET /runtime/status)
func (_ Unimplemented) GetRuntimeStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpgradeCelldDaemon Trigger zero-downtime rolling upgrade of the celld daemon across nodes
// (POST /runtime/upgrade)
func (_ Unimplemented) UpgradeCelldDaemon(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApplications(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateApplication(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApplication(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApplication operation middleware
func (siw *ServerInterfaceWrapper) DeleteApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApplication operation middleware
func (siw *ServerInterfaceWrapper) GetApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateApplication operation middleware
func (siw *ServerInterfaceWrapper) UpdateApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployApplication operation middleware
func (siw *ServerInterfaceWrapper) DeployApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDeployments operation middleware
func (siw *ServerInterfaceWrapper) ListDeployments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeployments(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestApplication operation middleware
func (siw *ServerInterfaceWrapper) TestApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeployment operation middleware
func (siw *ServerInterfaceWrapper) GetDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeploymentLogs operation middleware
func (siw *ServerInterfaceWrapper) GetDeploymentLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeploymentLogs(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDomains operation middleware
func (siw *ServerInterfaceWrapper) ListDomains(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDomains(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDomain operation middleware
func (siw *ServerInterfaceWrapper) CreateDomain(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDomain(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDomain operation middleware
func (siw *ServerInterfaceWrapper) DeleteDomain(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDomain(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodes operation middleware
func (siw *ServerInterfaceWrapper) ListNodes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNode operation middleware
func (siw *ServerInterfaceWrapper) CreateNode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNode operation middleware
func (siw *ServerInterfaceWrapper) DeleteNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNode operation middleware
func (siw *ServerInterfaceWrapper) GetNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DrainNode operation middleware
func (siw *ServerInterfaceWrapper) DrainNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DrainNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRuntimeStatus operation middleware
func (siw *ServerInterfaceWrapper) GetRuntimeStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRuntimeStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpgradeCelldDaemon operation middleware
func (siw *ServerInterfaceWrapper) UpgradeCelldDaemon(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpgradeCelldDaemon(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/nodes", wrapper.ListNodes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/nodes", wrapper.CreateNode)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/nodes/{id}", wrapper.DeleteNode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/nodes/{id}", wrapper.GetNode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/nodes/{id}/drain", wrapper.DrainNode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/applications", wrapper.ListApplications)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/applications", wrapper.CreateApplication)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/applications/{id}", wrapper.DeleteApplication)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/applications/{id}", wrapper.GetApplication)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/applications/{id}", wrapper.UpdateApplication)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/applications/{id}/deploy", wrapper.DeployApplication)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/applications/{id}/deployments", wrapper.ListDeployments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/applications/{id}/test", wrapper.TestApplication)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments/{id}", wrapper.GetDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments/{id}/logs", wrapper.GetDeploymentLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/domains", wrapper.ListDomains)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/domains", wrapper.CreateDomain)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/domains/{id}", wrapper.DeleteDomain)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runtime/status", wrapper.GetRuntimeStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runtime/upgrade", wrapper.UpgradeCelldDaemon)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fxtbxs3Ev4rPN4BbQFZL7bbODrcB8dOU+Pa1LCcHA69QKB2ZyXWXHJDcuWogf77geRql6ulpHUiSy36",
	"xZL4Mi/PzDwcsvmMI5FmggPXCg8/YwkqE1yB/fCKxHfwMQelzadIcA3c/kmyjNGIaCp473cluPlORTNI",
	"ifnrHxISPMR/71VL99yvqvdaSiHvik3wcrns4BhUJGlmFsNDsyeSblPUQ3PCaGz3QQmhLJeAlx18JXjC",
	"aHRAqVY7okeqZwg+UaUpnyIJSuQyskLdcA2SE2bXOpxkq22RAjkHicBuv+zgt0L/KHIeH06Uu8IaiAuN",
	"Eru3GVTMN8tfVpubj5kUGUhNHdpIpOkcriFjYpEC1zdW9ETIlGg8xHlOY9zBPGeMTBjgoZY5dLBeZICH",
	"WGlJ+dToPaE8pnxql6QaUrVLr5XYr9xEs0axKJGSLOyakvBoZhaKISE5M/KkhHIc2D+SQDTEl7omfUw0",
	"nGiaQmgK8Pl7IttL/JrPqRTcGOk9kdSaIyD1lOo7yIRZDT6RNDNGwzOtMzXs9aZUz/JJNxJpL10IOe2R",
	"jLYxLw16pTmMM8rhSsRQ3x4+ZUJqVJgRfUYJ6Gg2RN9K+Pgd+tf/8n7/DBCHR7RC2rff/ASMCfQfIVn8",
	"t2++Q8t/tpGTk3Rt63Rx8ijkA8gTp2pjioPBvf16uwNG1UgzTxOdW6cBz1M8/G2FAdzBk5wyi6oOljnn",
	"7i+lRZbZn01Sgxh/CEmTT2JhQfY0LTQo/U6ypteHvV5tcpeJiLCZUHp40e/3Q2vlWfw0LC872CRvKiE2",
	"dnARS+xIz7qlyfxo8Xer7CEmv0OkbdK3I70M4pWmeiI5dgb4E4XzoeISJVKk6CqfUF2G6PFCcg2Fdt/N",
	"kKoqzkZERSJNqf6JKIuAhpSJkBHcgY31GkQSwlSVnCZCMCDcyrdJFhvxG+XwivdNuzxswrtpdxP96SLK",
	"lRapSzIGOaH5GdGzWwkJ/VTHfm9n7Ndl9STZ7Im3IoaNutOC6NwKqWuyXPQvBuWSZtQULAGi2WUcS1Cq",
	"rvug3zX/DU7bQZSLGE4SSfhDkkt9MgjNchgOCdZvChYCpy9syDwVRPeBCYvT9yBVQcPqLG5kHMA1JQzZ",
	"gWjuRqJESKRnVCFvR/QtdKddNLA/zgff4U5luqBTJjmPGYzoH3Uzn39/2u/3QxPqoVf55UVyMXl5GgUZ",
	"mJ3yCyhFpmveTIDoIbqMY5vKMmJtioDHmaBc74vOGaLsbb+TqySUUzXbusm+eFnFVbYl0wpvIzc+WNjX",
	"I9xzVbDCb0f2z2L6mmu5aCKcwRyYT68oTwTu4EciTf11J54QhUpDEHhVMDLkoIhyZT6AsmDvdrthq0Hm",
	"CzClehwxwY1niplG5bNxnjFBrC2AsXgcW+0M9xO5hrFa8CgoqHGy0iTNvpBnVfMLWSvdO4X5tht/1KCw",
	"GfCCt3oU1unj/nbHtYrDGsaagVQQbyC01yWb/doE9gUx+bV1sGV4PaFcdrBS7NIZsR1n2BmApZI1QfyN",
	"doVjiIo2K7EaQSRBtxG7gx9gUTf65e3NePT66u71fcgoc8LyNS8pu9t4Tth4cHq2MxjMhqt1gjrW+hgB",
	"rrfOjd/+ej/+8dd3b69D8sagCWV1st+kFeHsXVL7YKLyjjqu7XRz7XVWdlnBqlGtHDLE20LTNf1N5vLY",
	"QSVQv3va7e8pHlu3EfZE+l6edgc/XHQH3e/7T+B9TPBY8DDpUxlEOwupMfHIDmxde+2Uoup+HbX0T9+V",
	"XdaMWtvCL9s+DHaljUrNJpyy/EpIqPvjIuS6mKqHHyXAq4VeGz7ovzh7cT64OD03HLEEDeX6h3McWiqF",
	"VMhFYKEXgxcvL354Obg4b7HOcpOmjWJZ1sJYElo0eUSSmKN2sBSuNxwaVmvi8Zf/jv/9PoTDVQ/a1c5q",
	"wsN8rLSQMCZZFgSwLk7VKyUe5mOzrcpIZFUZjGOiyYQo80mejid59AAGIx9zyKEATsLEY0DFdX7iuj4b",
	"j393OTeJojJsqDNsTK+uRO4OQaWiZ8FTQy4lcH319FxG1btsKsnKLeWMjfXNGJlM4RWJHsB120uWSMwP",
	"Y9tmMyHERB4njEgYS3P4JI9qrEw5c/zD/P3BOz6tT2/6j8gpbFXxzKq44+iwfmxft3XYmHVDhXw6qrVu",
	"Kio0pWZNj0njVVcqGCr3oHSrpp+IF8HaOwMSg+vGkTimZhHCbmtzN4SGp0wKeibqvR38xhKYyt5vwoTG",
	"MLEmGaymhTspDQkadtjEX1aGqHbY0KcL0uR9GMvVkEaP8bS/u2R5UztOkxC03tlG8fFbwYfq/Nabti3A",
	"4iITrgmkW4zjEsjW3LEjrdcWaHpqaWVPRKDJpCWNNLp7PbpHl7c3tn1kUdlBhCORAT8p7hInRMJJCpow",
	"dEvIyI4sblLQVZlRDbofQCpEeIyuc2ksiX61YqjihG8JTQfdSwIJfejYkaMzVKRve+yn2ipvBUFXgmsp",
	"GLplhIMR0hwqVrbCg26/2zemNrKSjOIhPusOrM1MwFv79rzzmf1i6s5MxgflcRf/TGuBbbhX7RL+tN9/",
	"0hVuK+D5F7ENwDVvdo2MSCSoptCyg793soV2KnXo1S/G7Y1wnqZELlYLE8bqK5vaZmK21kRW+IPJpkIF",
	"bNi4G8IOqKD0qyId7uUKfOMd1LIeGqbQLht+HOxNjpr7mu7yT46rq8hlB5+38Zb35sNOebl7SvkcYx+I",
	"cCZGxDZoSc2jG0Cx7NQjrfeZxkuXchhoaKLl2n6/jpaaq86bKcs3qlu5MOr5boXLtxj7sJAT3+RJvxFv",
	"0llkOCnKM0S1QrbluDWWgunoDeitlukfA8SrJstR7P0GdM3SK2G2ZSkiSQraMqnfPmNq9LE8cNVpcGfz",
	"esLoeHbb0RhZfujgLA94r8GMnikRbmRgrRLhUTBUvC744kR4aNg5E9eQFwme0GkuvyQh9oq7CMMCD4HO",
	"YJ12Fw6HqtPNi/1lAc8aGk/3tq13TRsAY/UrIlEEmYbYZm3bTjlSLbmXdDoFWZTbuJLQ0Ox6hfHwVo3b",
	"Bbd09a50I/W99sYdgvn6PtpNfD2fzag5KiyO4yfLk+OGME9x0yGqUhgKenX6PFreWWuePFPW2dCqCiad",
	"/vPtuvWBbs7sQU7PABm3IMrnojoHHh7YI+AxIk6Wn+7vb8u331pYIV070oe+OYby9icDLwjKg8Em4uvl",
	"hmd0WOsqocpboOOQXs/oBee19aq8Ijpunll3bI+JqWrn3Z/NyMMWm/J1S4uiY1+oIKvOn8H37hWY8Tx8",
	"gii3TJQ5Cx4ZAfbFxg56UYw5iLfdA5cn9NPczQ9aKbLXjlptbVQ2wj2nFbvuaqsVaj0rU689ez1wM23l",
	"tkAudraznZS/XCPtMjaFtY4Cq0kQAl48teyfebDY1Tor7HjUrtkdpGIOT7DIobIYFzFsz2H2MvYgGcy+",
	"CGqRvy4RKzKYhClVGiTE/k2N02mv6SxhALpYuHKX+7wrg71194nPl7/8h+sHzl7OZU0Xme9976g8ikCp",
	"JGds8ZfJYXeF/EV/Yg1hARyUAdUyiZXI2JXCrDl9GyJpE8rR7gCkZxojm73YNycmGyjBENlEjMNG6B8G",
	"okdv7XNPCjRZoJvrcH45XDEoGmhy9Vr6eO1aI8Jx0WEkCGavg0eckWQVbFogRRJgC5TSqSQa7I1b0auo",
	"Pz9ADIgK1izjb+kevvWqp6GbgrT+RO4Z/VHfKNRFcgOKPgAikRRKFWlnX0Hpqr1c24nH7hVH+b8kUe6w",
	"Xe8CFdPWTJy7NzE2ooJoLx7N2Gdu7uXMs12eBV7ntKINpwf0smCM8ikqzIYop5p+xQFob1cVf4AUJ7F4",
	"dNCQa2IWvU0Hk9haeIXQde7owcRsZP/5BJdi1/7tB/sc6PL2Bs0HuINzyfAQ90hGe/MBXn5Y/j8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
