// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApplicationStatus.
const (
	ApplicationStatusBuilding ApplicationStatus = "building"
	ApplicationStatusCreated  ApplicationStatus = "created"
	ApplicationStatusFailed   ApplicationStatus = "failed"
	ApplicationStatusRunning  ApplicationStatus = "running"
	ApplicationStatusStopped  ApplicationStatus = "stopped"
)

// Valid indicates whether the value is a known member of the ApplicationStatus enum.
func (e ApplicationStatus) Valid() bool {
	switch e {
	case ApplicationStatusBuilding:
		return true
	case ApplicationStatusCreated:
		return true
	case ApplicationStatusFailed:
		return true
	case ApplicationStatusRunning:
		return true
	case ApplicationStatusStopped:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentLogEntryLevel.
const (
	Error DeploymentLogEntryLevel = "error"
	Info  DeploymentLogEntryLevel = "info"
	Warn  DeploymentLogEntryLevel = "warn"
)

// Valid indicates whether the value is a known member of the DeploymentLogEntryLevel enum.
func (e DeploymentLogEntryLevel) Valid() bool {
	switch e {
	case Error:
		return true
	case Info:
		return true
	case Warn:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentLogEntryStep.
const (
	CelldDeploy DeploymentLogEntryStep = "celld_deploy"
	Esbuild     DeploymentLogEntryStep = "esbuild"
	GitClone    DeploymentLogEntryStep = "git_clone"
	RouteSync   DeploymentLogEntryStep = "route_sync"
	S3Upload    DeploymentLogEntryStep = "s3_upload"
)

// Valid indicates whether the value is a known member of the DeploymentLogEntryStep enum.
func (e DeploymentLogEntryStep) Valid() bool {
	switch e {
	case CelldDeploy:
		return true
	case Esbuild:
		return true
	case GitClone:
		return true
	case RouteSync:
		return true
	case S3Upload:
		return true
	default:
		return false
	}
}

// Defines values for DeploymentStatus.
const (
	DeploymentStatusActive     DeploymentStatus = "active"
	DeploymentStatusBuilding   DeploymentStatus = "building"
	DeploymentStatusDeploying  DeploymentStatus = "deploying"
	DeploymentStatusFailed     DeploymentStatus = "failed"
	DeploymentStatusPending    DeploymentStatus = "pending"
	DeploymentStatusSuperseded DeploymentStatus = "superseded"
)

// Valid indicates whether the value is a known member of the DeploymentStatus enum.
func (e DeploymentStatus) Valid() bool {
	switch e {
	case DeploymentStatusActive:
		return true
	case DeploymentStatusBuilding:
		return true
	case DeploymentStatusDeploying:
		return true
	case DeploymentStatusFailed:
		return true
	case DeploymentStatusPending:
		return true
	case DeploymentStatusSuperseded:
		return true
	default:
		return false
	}
}

// Defines values for NodeStatus.
const (
	NodeStatusActive   NodeStatus = "active"
	NodeStatusDraining NodeStatus = "draining"
	NodeStatusOffline  NodeStatus = "offline"
)

// Valid indicates whether the value is a known member of the NodeStatus enum.
func (e NodeStatus) Valid() bool {
	switch e {
	case NodeStatusActive:
		return true
	case NodeStatusDraining:
		return true
	case NodeStatusOffline:
		return true
	default:
		return false
	}
}

// Defines values for ResourceBindingType.
const (
	D1Database  ResourceBindingType = "d1_database"
	KvNamespace ResourceBindingType = "kv_namespace"
	Queue       ResourceBindingType = "queue"
	R2Bucket    ResourceBindingType = "r2_bucket"
	Workflow    ResourceBindingType = "workflow"
)

// Valid indicates whether the value is a known member of the ResourceBindingType enum.
func (e ResourceBindingType) Valid() bool {
	switch e {
	case D1Database:
		return true
	case KvNamespace:
		return true
	case Queue:
		return true
	case R2Bucket:
		return true
	case Workflow:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeStatusStorageBackend.
const (
	AwsS3        RuntimeStatusStorageBackend = "aws_s3"
	CloudflareR2 RuntimeStatusStorageBackend = "cloudflare_r2"
	CustomS3     RuntimeStatusStorageBackend = "custom_s3"
	GarageLocal  RuntimeStatusStorageBackend = "garage_local"
)

// Valid indicates whether the value is a known member of the RuntimeStatusStorageBackend enum.
func (e RuntimeStatusStorageBackend) Valid() bool {
	switch e {
	case AwsS3:
		return true
	case CloudflareR2:
		return true
	case CustomS3:
		return true
	case GarageLocal:
		return true
	default:
		return false
	}
}

// Application defines model for Application.
type Application struct {
	ActiveDeploymentId *openapi_types.UUID    `json:"activeDeploymentId,omitempty"`
	Bindings           *[]ResourceBinding     `json:"bindings,omitempty"`
	Branch             string                 `json:"branch"`
	CreatedAt          time.Time              `json:"createdAt"`
	EnvVars            *[]EnvironmentVariable `json:"envVars,omitempty"`
	GitRepo            string                 `json:"gitRepo"`
	Id                 openapi_types.UUID     `json:"id"`
	Name               string                 `json:"name"`
	Status             ApplicationStatus      `json:"status"`
	UpdatedAt          time.Time              `json:"updatedAt"`
}

// ApplicationStatus defines model for Application.Status.
type ApplicationStatus string

// CreateApplicationRequest defines model for CreateApplicationRequest.
type CreateApplicationRequest struct {
	Bindings *[]ResourceBinding     `json:"bindings,omitempty"`
	Branch   *string                `json:"branch,omitempty"`
	EnvVars  *[]EnvironmentVariable `json:"envVars,omitempty"`
	GitRepo  string                 `json:"gitRepo"`
	Name     string                 `json:"name"`
}

// CreateDeploymentRequest defines model for CreateDeploymentRequest.
type CreateDeploymentRequest struct {
	CommitHash   *string `json:"commitHash,omitempty"`
	ForceRebuild *bool   `json:"forceRebuild,omitempty"`
}

// CreateDomainRequest defines model for CreateDomainRequest.
type CreateDomainRequest struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`
	Hostname      string             `json:"hostname"`
	PathPrefix    *string            `json:"pathPrefix,omitempty"`
}

// CreateNodeRequest defines model for CreateNodeRequest.
type CreateNodeRequest struct {
	InternalPort *int   `json:"internalPort,omitempty"`
	IpAddress    string `json:"ipAddress"`
	Name         string `json:"name"`
	WorkerPort   *int   `json:"workerPort,omitempty"`
}

// Deployment defines model for Deployment.
type Deployment struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`
	BundleSize    *int               `json:"bundleSize,omitempty"`
	CommitHash    string             `json:"commitHash"`
	CommitMessage *string            `json:"commitMessage,omitempty"`
	CreatedAt     time.Time          `json:"createdAt"`
	ErrorMessage  *string            `json:"errorMessage,omitempty"`
	FinishedAt    *time.Time         `json:"finishedAt,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	Status        DeploymentStatus   `json:"status"`
}

// DeploymentLogEntry defines model for DeploymentLogEntry.
type DeploymentLogEntry struct {
	Level     DeploymentLogEntryLevel `json:"level"`
	Message   string                  `json:"message"`
	Step      DeploymentLogEntryStep  `json:"step"`
	Timestamp time.Time               `json:"timestamp"`
}

// DeploymentLogEntryLevel defines model for DeploymentLogEntry.Level.
type DeploymentLogEntryLevel string

// DeploymentLogEntryStep defines model for DeploymentLogEntry.Step.
type DeploymentLogEntryStep string

// DeploymentStatus defines model for DeploymentStatus.
type DeploymentStatus string

// Domain defines model for Domain.
type Domain struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`
	CreatedAt     time.Time          `json:"createdAt"`
	Hostname      string             `json:"hostname"`
	Id            openapi_types.UUID `json:"id"`
	PathPrefix    string             `json:"pathPrefix"`
	SslActive     bool               `json:"sslActive"`
}

// EnvironmentVariable defines model for EnvironmentVariable.
type EnvironmentVariable struct {
	IsSecret *bool  `json:"isSecret,omitempty"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string    `json:"code"`
	Details *[]string `json:"details,omitempty"`
	Message string    `json:"message"`
}

// Node defines model for Node.
type Node struct {
	CelldVersion string             `json:"celldVersion"`
	CreatedAt    time.Time          `json:"createdAt"`
	Id           openapi_types.UUID `json:"id"`
	InternalPort int                `json:"internalPort"`
	IpAddress    string             `json:"ipAddress"`
	Name         string             `json:"name"`
	Specs        *NodeSpecs         `json:"specs,omitempty"`
	Status       NodeStatus         `json:"status"`
	WorkerPort   int                `json:"workerPort"`
}

// NodeSpecs defines model for NodeSpecs.
type NodeSpecs struct {
	CpuCores      *int   `json:"cpuCores,omitempty"`
	DiskFreeBytes *int64 `json:"diskFreeBytes,omitempty"`
	MemoryBytes   *int64 `json:"memoryBytes,omitempty"`
}

// NodeStatus defines model for NodeStatus.
type NodeStatus string

// ResourceBinding defines model for ResourceBinding.
type ResourceBinding struct {
	Name       string              `json:"name"`
	ResourceId *string             `json:"resourceId,omitempty"`
	Type       ResourceBindingType `json:"type"`
}

// ResourceBindingType defines model for ResourceBinding.Type.
type ResourceBindingType string

// RuntimeStatus defines model for RuntimeStatus.
type RuntimeStatus struct {
	ActiveNodesCount    int                          `json:"activeNodesCount"`
	CurrentCelldVersion string                       `json:"currentCelldVersion"`
	IsUpgrading         bool                         `json:"isUpgrading"`
	StorageBackend      *RuntimeStatusStorageBackend `json:"storageBackend,omitempty"`
	TargetCelldVersion  *string                      `json:"targetCelldVersion,omitempty"`
}

// RuntimeStatusStorageBackend defines model for RuntimeStatus.StorageBackend.
type RuntimeStatusStorageBackend string

// UpdateApplicationRequest defines model for UpdateApplicationRequest.
type UpdateApplicationRequest struct {
	Bindings *[]ResourceBinding     `json:"bindings,omitempty"`
	Branch   *string                `json:"branch,omitempty"`
	EnvVars  *[]EnvironmentVariable `json:"envVars,omitempty"`
}

// UpgradeDaemonRequest defines model for UpgradeDaemonRequest.
type UpgradeDaemonRequest struct {
	TargetVersion string `json:"targetVersion"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = CreateApplicationRequest

// UpdateApplicationJSONRequestBody defines body for UpdateApplication for application/json ContentType.
type UpdateApplicationJSONRequestBody = UpdateApplicationRequest

// DeployApplicationJSONRequestBody defines body for DeployApplication for application/json ContentType.
type DeployApplicationJSONRequestBody = CreateDeploymentRequest

// CreateDomainJSONRequestBody defines body for CreateDomain for application/json ContentType.
type CreateDomainJSONRequestBody = CreateDomainRequest

// CreateNodeJSONRequestBody defines body for CreateNode for application/json ContentType.
type CreateNodeJSONRequestBody = CreateNodeRequest

// UpgradeCelldDaemonJSONRequestBody defines body for UpgradeCelldDaemon for application/json ContentType.
type UpgradeCelldDaemonJSONRequestBody = UpgradeDaemonRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListApplications List all applications
	// (GET /applications)
	ListApplications(w http.ResponseWriter, r *http.Request)
	// CreateApplication Create a new application
	// (POST /applications)
	CreateApplication(w http.ResponseWriter, r *http.Request)
	// DeleteApplication Delete an application and clean up its routes
	// (DELETE /applications/{id})
	DeleteApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetApplication Get application details
	// (GET /applications/{id})
	GetApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateApplication Update application configuration
	// (PUT /applications/{id})
	UpdateApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// DeployApplication Trigger a new deployment for an application
	// (POST /applications/{id}/deploy)
	DeployApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListDeployments List deployment history for an application
	// (GET /applications/{id}/deployments)
	ListDeployments(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetDeployment Get deployment details and status
	// (GET /deployments/{id})
	GetDeployment(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetDeploymentLogs Get deployment build and execution logs
	// (GET /deployments/{id}/logs)
	GetDeploymentLogs(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListDomains List all custom domain bindings
	// (GET /domains)
	ListDomains(w http.ResponseWriter, r *http.Request)
	// CreateDomain Add a custom domain route
	// (POST /domains)
	CreateDomain(w http.ResponseWriter, r *http.Request)
	// DeleteDomain Remove a custom domain route
	// (DELETE /domains/{id})
	DeleteDomain(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ListNodes List all fleet nodes
	// (GET /nodes)
	ListNodes(w http.ResponseWriter, r *http.Request)
	// CreateNode Register a new bare-metal node
	// (POST /nodes)
	CreateNode(w http.ResponseWriter, r *http.Request)
	// DeleteNode Deregister a node from the fleet
	// (DELETE /nodes/{id})
	DeleteNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetNode Get node details by ID
	// (GET /nodes/{id})
	GetNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// DrainNode Drain a node to safely migrate its active Durable Object leases
	// (POST /nodes/{id}/drain)
	DrainNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetRuntimeStatus Get fleet runtime status and celld version information
	// (GET /runtime/status)
	GetRuntimeStatus(w http.ResponseWriter, r *http.Request)
	// UpgradeCelldDaemon Trigger zero-downtime rolling upgrade of the celld daemon across nodes
	// (POST /runtime/upgrade)
	UpgradeCelldDaemon(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// ListApplications List all applications
// (GET /applications)
func (_ Unimplemented) ListApplications(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateApplication Create a new application
// (POST /applications)
func (_ Unimplemented) CreateApplication(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteApplication Delete an application and clean up its routes
// (DELETE /applications/{id})
func (_ Unimplemented) DeleteApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetApplication Get application details
// (GET /applications/{id})
func (_ Unimplemented) GetApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateApplication Update application configuration
// (PUT /applications/{id})
func (_ Unimplemented) UpdateApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeployApplication Trigger a new deployment for an application
// (POST /applications/{id}/deploy)
func (_ Unimplemented) DeployApplication(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListDeployments List deployment history for an application
// (GET /applications/{id}/deployments)
func (_ Unimplemented) ListDeployments(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetDeployment Get deployment details and status
// (GET /deployments/{id})
func (_ Unimplemented) GetDeployment(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetDeploymentLogs Get deployment build and execution logs
// (GET /deployments/{id}/logs)
func (_ Unimplemented) GetDeploymentLogs(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListDomains List all custom domain bindings
// (GET /domains)
func (_ Unimplemented) ListDomains(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateDomain Add a custom domain route
// (POST /domains)
func (_ Unimplemented) CreateDomain(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteDomain Remove a custom domain route
// (DELETE /domains/{id})
func (_ Unimplemented) DeleteDomain(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListNodes List all fleet nodes
// (GET /nodes)
func (_ Unimplemented) ListNodes(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateNode Register a new bare-metal node
// (POST /nodes)
func (_ Unimplemented) CreateNode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteNode Deregister a node from the fleet
// (DELETE /nodes/{id})
func (_ Unimplemented) DeleteNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetNode Get node details by ID
// (GET /nodes/{id})
func (_ Unimplemented) GetNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DrainNode Drain a node to safely migrate its active Durable Object leases
// (POST /nodes/{id}/drain)
func (_ Unimplemented) DrainNode(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetRuntimeStatus Get fleet runtime status and celld version information
// (GET /runtime/status)
func (_ Unimplemented) GetRuntimeStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpgradeCelldDaemon Trigger zero-downtime rolling upgrade of the celld daemon across nodes
// (POST /runtime/upgrade)
func (_ Unimplemented) UpgradeCelldDaemon(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApplications(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateApplication(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApplication(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApplication operation middleware
func (siw *ServerInterfaceWrapper) DeleteApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApplication operation middleware
func (siw *ServerInterfaceWrapper) GetApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateApplication operation middleware
func (siw *ServerInterfaceWrapper) UpdateApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeployApplication operation middleware
func (siw *ServerInterfaceWrapper) DeployApplication(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeployApplication(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDeployments operation middleware
func (siw *ServerInterfaceWrapper) ListDeployments(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDeployments(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeployment operation middleware
func (siw *ServerInterfaceWrapper) GetDeployment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeployment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeploymentLogs operation middleware
func (siw *ServerInterfaceWrapper) GetDeploymentLogs(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeploymentLogs(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDomains operation middleware
func (siw *ServerInterfaceWrapper) ListDomains(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDomains(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDomain operation middleware
func (siw *ServerInterfaceWrapper) CreateDomain(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDomain(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDomain operation middleware
func (siw *ServerInterfaceWrapper) DeleteDomain(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDomain(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodes operation middleware
func (siw *ServerInterfaceWrapper) ListNodes(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodes(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNode operation middleware
func (siw *ServerInterfaceWrapper) CreateNode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNode operation middleware
func (siw *ServerInterfaceWrapper) DeleteNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNode operation middleware
func (siw *ServerInterfaceWrapper) GetNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DrainNode operation middleware
func (siw *ServerInterfaceWrapper) DrainNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DrainNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRuntimeStatus operation middleware
func (siw *ServerInterfaceWrapper) GetRuntimeStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRuntimeStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpgradeCelldDaemon operation middleware
func (siw *ServerInterfaceWrapper) UpgradeCelldDaemon(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpgradeCelldDaemon(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/nodes", wrapper.ListNodes)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/nodes", wrapper.CreateNode)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/nodes/{id}", wrapper.DeleteNode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/nodes/{id}", wrapper.GetNode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/nodes/{id}/drain", wrapper.DrainNode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/applications", wrapper.ListApplications)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/applications", wrapper.CreateApplication)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/applications/{id}", wrapper.DeleteApplication)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/applications/{id}", wrapper.GetApplication)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/applications/{id}", wrapper.UpdateApplication)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/applications/{id}/deploy", wrapper.DeployApplication)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/applications/{id}/deployments", wrapper.ListDeployments)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments/{id}", wrapper.GetDeployment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/deployments/{id}/logs", wrapper.GetDeploymentLogs)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/domains", wrapper.ListDomains)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/domains", wrapper.CreateDomain)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/domains/{id}", wrapper.DeleteDomain)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/runtime/status", wrapper.GetRuntimeStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/runtime/upgrade", wrapper.UpgradeCelldDaemon)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Ftrb9u40v4rBN/3o+JLkt2m/pZb9wSnmwZJ24ODRWHQ0sjhhiK1JOXUW/i/H5CULUqiLad17C76JbZ5",
	"mXnmmQuH7DcciywXHLhWePQNS1C54ArshwuS3MNfBShtPsWCa+D2T5LnjMZEU8H7fyrBzXcqfoSMmL/+",
	"X0KKR/j/+tXSffer6l9LKeR9uQleLBYRTkDFkuZmMTwyeyLpNkV9NCOMJnYflBLKCgl4EeFLwVNG4z1K",
	"tdwRPVP9iOArVZryKZKgRCFjK9QN1yA5YXat/Um23BYpkDOQCOz2iwjfCv1OFDzZnyj3JRqIC41Su7cZ",
	"VM43y59Xm5uPuRQ5SE0d20is6QyuIGdingHXN1b0VMiMaDzCRUETHGFeMEYmDPBIywIirOc54BFWWlI+",
	"NXpPKE8on9olqYZMdem1FPvCTTRrlIsSKcncrikJjx/NQgmkpGBGnoxQjgP7xxKIhuRc16RPiIYjTTMI",
	"TQE++0zk9hJf8xmVghuQPhNJLRwBqadU30MuzGrwlWS5AQ0/ap2rUb8/pfqxmPRikfWzuZDTPslpSDYa",
	"tEJrGCcZ1DfK5kfPQj6BPFqzstJEF1ZX4EWGR38socMRnhSUWWNEWBacu7+UFnlufzaxABL8JbBqkScv",
	"g38RYRNvqITEyOBIRuzIJYArAqyE9s3s71lJJCZ/QqxttLIjPep7MbXuAYem7s/MwxcTrGHXhknXG6oK",
	"QGvtFIsso/pfRFlcW6KmQsZwD5bDNeBTwlQVsiZCMCDcSrpOFmFMtVYOL5bfbOemj0LpNpIkp71sHhdK",
	"iyyxWxp7hObnRD/eSUjp1zqj+p3412X1JFlviVuRwFrdaZn37oTUNVnOBmfD1ZJm1BRsPqT5eZJIUKqu",
	"+3DQM/+Gx9uRjosEjlJJ+FNaSH00DM1yrAwJNmgLFqZpJWwInoqiu+DEpOAJgwf6d13V01+OB4NBCMk6",
	"/Sts3qRnk7fHcTAp2im/g1Jk2kA0BaJH6DxJEIdnlBOrFwKe5IJyvasMa2oXb/vOKiKlnKrHjZt0rrFl",
	"6qzy4KZYW9n8wY0PJq6ml3mmCuauzex6L6bXXMt5m2UMZsD81E15avLkM5Ems7giNJSesxAFLspsjxwV",
	"UaHMB1A2gvZ6vTBqkPsCTKkex0xwY5lyplH5ZFzkTBCLBTCWjBOrnakrRKFhrOY8DgpqjKw0yfLvrCOq",
	"+aWsle5RCd9m8B9a5VEOvKyJvPLI6eP+dhV0VR9FWBU5SAXJmmLJ5ZddBJHv8MkfzUVbutcLUlaElWLn",
	"DsTt8nanA66UrAnib9TljqEiq50N1QPEEvQ2Ykf4CeZ10M/vbsYP15f31x9DoMwIKxpWUna38Yyw8fD4",
	"pNMZzIbLdYI61o6WgXoraex/++Hj+N2HT7dXIXkT0ISyehnbTu3h6L0qWoOByiviXSfg5so77HahYNWo",
	"Vg4BcVtq2tDfRK7PIFV5bq4EGvSOe4Md+eOW/rSzwuvtcW/461lv2Ptl8ILaiwmeCB4uvFQOcWciNRA/",
	"2IFb5147pcy6P1be+afLCpcGqLUt/LTt06ArbFRqtumUF5dCQt0eZyHTJVQ9vZMAF3PdGD4cvDl5czo8",
	"Oz41NeKKNJTrX09xaKkMMiHngYXeDN+8Pfv17fDsdIt1Fus0bSXLVS5MJKFlA0GkKaMcgqmweZRuodbm",
	"4+//Hf/7c4iHy7agy53VhKfZWGkhYUzyPEhg90WlxNNsbLZVOYmtKsNxQjSZEGU+yePxpIifwHDkrwIK",
	"KImTMvEcULFZn5hfSy6G+HNfcBMoKmBDzToDvboUhTuIrBQ9CZ4aCimB68uXxzKqPuVTSZZmWc1Ym98M",
	"yGQKFyR+AtcAXVWJxPwwZiImzLgQE0WSMiJhLM0BkDyrsTLpzNUf5u8vkSdiY3rbfkROYaOKJ1bFjqND",
	"8+jcxDoMZh2okE0/2T7V4TtR+2k8LYIIGHzgikC2QXtnxo0W7HCu2gJtUyxsHk2FSyB+D/1BSxprdH/9",
	"8BGd392gVEh0WUyojhDhSOTAj8om+4RIOMpAE4buCHmwI8teKbpc8Rr9x6YShQhP0FUhDVTogxVDlecs",
	"m1Yi9FESSOlTZEc+nKDSiezhi2qrvBUEXQqupWDojhEORkhT2i2xwsPeoDcwUBtZSU7xCJ/0hhYzUwBb",
	"fPtelWy/mLrK1dhgdejA76nS5/7AqH47dTwYvOhuYytm+TcUbUa1rjyMjEikqKbQIsK/ONlCO6106Ndv",
	"jOxVSZFlxJy33cKEsfrKJsIYp6y10xT+Yo45QgUwbPWesSMqKH0hkvnO7obW9rgXddcw4W7RsuNwZ3LU",
	"zNc2l1+/Ly8bFhE+3cZa3mWonfK2e8rqnnIXjHAQI2LbZKRm0TWkWER1T+t/o8nChRwGGtpsubLfN9lS",
	"M9VpO2T5oLqVS1BPuxVeXVLuAiEnvomTntY2nMWmMkBFjqhWyDZ+NvpSMBz9BnojMoNDkHh51D0I3r+B",
	"riG9FGZTlCKSZKDB5Po/vmFq9DFpYVmJjtwJqR4wIg+3juPp4kuE8yJgvVbp80qBcG2JtVUgPAiHytvL",
	"7w6E+6adg7jGvFjwlE4L+T0BsV92hE0VuA92BvO0a/vuK0+3rzgXJT1rbDze2bbehVWAjNWviMQx5BoS",
	"G7XtofZAueSjpNMpyDLdJpWEpsyuZxiPb9W4LrplywdXa0vfK2/cPipf30bdha9ns0dqjgrzw9jJ1slJ",
	"S5iXmGkfWclQwdt1VYmtqzQ8Y7xiktjaLdWq+XmYKsMzcFlk2ACx6oz+XIbtMzFV21n3vRm5X+9eXepu",
	"4eX2YhZZdX4G29trT2t5+ApxYVM/cwgemAH2orIjnpdj9mJtd6/7ggaGa3iipSI7bWHU1kar1qJntHLX",
	"rj5Gqdarlka1F1d77l4szRaIxQ47e3T9x3UuzpMEkQYLrCZBCnj+tGXDwqNFV6+ixPGgbYp7yMQMXoDI",
	"vqIYFwlsjmH2DmIvEcxehG8Rv84RKyOYhClVGiQkfmvc6bTTcJYyAF0uXJnLfe6KYLfuCcDrxS//zeSe",
	"o5czWdtE5nvfOqqIY1AqLRib/2Ni2H0pf3kgbDAswIOVQ20ZxFbM6AphFk4fQyRtQDlY01V60BjZUiky",
	"pB/BOUrQRdYVxmEQBvuh6MF7qdyTAk3m6OYqHF/2lwzKjoVcPhI8XH/MiHBYdhgJgtFr7x5nJFk6mxZI",
	"kRTYHGV0KokGe8XhXgw07nsRA6KCOcvYW7r3Hv3qRdQ6J62/DHlFe9Q3Cv2HMzeg7AMgEkuhVBl2duWU",
	"LtvLxk48cdfmqLz4RpQ7btcbTeW0BsSFe4RgPSrI9vKVgn3d4Z4qvNptReA5xFZlw/EerSwYo3yKStgQ",
	"5VTTHzgA7aw3/DdIcZSIZ0cN2RBTpDYJOpokFuElQ5u1o0cTs5H9j5wuxDb+F6p9f3F+d4NmQxzhQjI8",
	"wn2S0/5siBdfFv8LAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
